.TH "chinese-checkers-gui" 6 "May 1, 2013" "Chinese Checkers game, GUI"
.SH "NAME" 
chinese-checkers-gui \(em Implements a GUI to play chinese checkers in multiplayer.
.SH "SYNOPSIS" 
.PP 
\fBchinese-checkers-gui\fR

.SH "DESCRIPTION" 
.PP 
This program provides an UI to connect, launch a server and play a chinese checkers game.
 
.SH "OPTIONS" 
.PP 
Usual QT options apply.

.SH "AUTHOR" 
.PP 
This manual page was written by Salvo 'LtWorf' Tomaselli <tiposchi@tiscali.it> for 
the \fBDebian GNU/Linux\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License 
version 3 or any later version published by the Free Software Foundation. 
