.TH "chinese-checkers-bot" 6 "May 1, 2013" "Chinese checkers AI"
.SH "NAME" 
chinese-checkers-bot \(em Python implementation of a chinese checkers AI.
.SH "SYNOPSIS" 
.PP 
\fBchinese-checkers-bot\fR [OPTIONS\fR\fP]

.SH "DESCRIPTION" 
.PP 
This program provides an AI that playes chinese checkers. It needs to connect to a server provided by chinese-checkers-server.
 
.SH "OPTIONS" 
.PP 
These programs follow the usual GNU command line syntax, 
with long options starting with two dashes (`\-').  A summary of 
options is included below. However, the ordering is very strict \- 
.IP "\fB-h\fP
Shows help.

.IP "\fB-s\fP
Server hostname. The default is localhost.

.IP "\fB-p\fP
Server port. The default is 8000

.IP "\fB-n\fP
Nickname for the bot to use.

.IP "\fB-b\fP
Personality id.

.IP "\fB-l\fP
List personalities and exists.

.IP "\fB-g\fP
Name of the game to join. Can't be used when the AI has to host a game.

.IP "\fB-H\fP
Name of the game to host. Can't be used when the AI has to join a game.

.IP "\fB-y\fP
number of players to in the match before starting the game. Ignored when not hosting a game.

.SH "AUTHOR" 
.PP 
This manual page was written by Salvo 'LtWorf' Tomaselli <tiposchi@tiscali.it> for 
the \fBDebian GNU/Linux\fP system (but may be used by others).  Permission is 
granted to copy, distribute and/or modify this document under 
the terms of the GNU General Public License 
version 3 or any later version published by the Free Software Foundation. 
