#!/bin/sh
#$INSTDIR must be set

if test -e $INSTDIR
then
	cd $INSTDIR
else
	cd /usr/share/games/chinese-checkers-server
fi

if test -z $1
    then
        if test -z $PORT
        then
            PORT=8000
        fi
    else
        PORT=$1
fi

exec erl -cc port $PORT -pa ebin -eval "application:start(cc)." -noshell
